SET ANSI_NULLS ON;
SET ANSI_PADDING ON;
SET ANSI_WARNINGS ON;
SET ARITHABORT ON;
SET CONCAT_NULL_YIELDS_NULL ON;
SET QUOTED_IDENTIFIER ON;
GO
IF NOT EXISTS (
	SELECT 1
	FROM sys.sequences seq
	INNER JOIN sys.schemas sch ON seq.schema_id = sch.schema_id
	WHERE seq.name = N'SeqAuditCallStack' AND sch.name = N'AuditCallStack'
)
BEGIN
	CREATE SEQUENCE [AuditCallStack].[SeqAuditCallStack] 
	AS [bigint]
	START WITH 0
	INCREMENT BY 1
	MINVALUE -9223372036854775808
	MAXVALUE 9223372036854775807
	CACHE  1000;
END;