SET ANSI_NULLS ON;
SET ANSI_PADDING ON;
SET ANSI_WARNINGS ON;
SET ARITHABORT ON;
SET CONCAT_NULL_YIELDS_NULL ON;
SET QUOTED_IDENTIFIER ON;
GO
CREATE OR ALTER FUNCTION [AuditCallStack].[GetXESessionFileName](@IsTemp BIT, @IncludeWildcard BIT) RETURNS NVARCHAR(260)
AS
BEGIN
	RETURN dbo.GetXEFileDirectoryConfig() + AuditCallStack.GetXESessionName(@IsTemp) + CASE WHEN @IncludeWildcard = 1 THEN N'*' ELSE N'' END + N'.xel';
END;