SET ANSI_NULLS ON;
SET ANSI_PADDING ON;
SET ANSI_WARNINGS ON;
SET ARITHABORT ON;
SET CONCAT_NULL_YIELDS_NULL ON;
SET QUOTED_IDENTIFIER ON;
GO
CREATE OR ALTER FUNCTION [dbo].[GetXEFileDirectoryConfig]() RETURNS NVARCHAR(260)
AS
BEGIN
	RETURN (
		SELECT XEFileDirectory
		FROM dbo.XEFileDirectoryConfig
	);
END;