SET ANSI_NULLS ON;
SET ANSI_PADDING ON;
SET ANSI_WARNINGS ON;
SET ARITHABORT ON;
SET CONCAT_NULL_YIELDS_NULL ON;
SET QUOTED_IDENTIFIER ON;
GO
CREATE OR ALTER PROCEDURE [dbo].[StartXE] (@SessionName SYSNAME)
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @SQLForStart NVARCHAR(4000);

	IF EXISTS (SELECT 1 FROM sys.server_event_sessions WHERE [name] = @SessionName) AND
		NOT EXISTS (SELECT 1 FROM sys.dm_xe_sessions WHERE [name] = @SessionName)
	BEGIN
		SET @SQLForStart = N'ALTER EVENT SESSION ' + QUOTENAME(@SessionName) + N' ON SERVER STATE = START';
		EXEC sp_executesql @SQLForStart;			
	END;

	RETURN;
END;
