SET ANSI_NULLS ON;
SET ANSI_PADDING ON;
SET ANSI_WARNINGS ON;
SET ARITHABORT ON;
SET CONCAT_NULL_YIELDS_NULL ON;
SET QUOTED_IDENTIFIER ON;
GO
CREATE OR ALTER PROCEDURE [dbo].[SleepByMS] (@SleepMS INT)
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @sql NVARCHAR(4000);

	SELECT @sql = N'WAITFOR DELAY ''' + CAST(CAST(DATEADD(MILLISECOND, @SleepMS, '00:00:00') AS TIME(3)) AS NVARCHAR(20)) + '''';

	EXEC sp_executesql @sql;
	
	RETURN;
END;